version: "3.9"

services:
  lanqin-email:
    build:
      context: ..
      dockerfile: deploy/all-in-one/Dockerfile
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
      - "25:25"
      - "587:587"
      - "993:993"
    volumes:
      - lanqin-data:/data
      - maildata:/var/mail/vhosts
      - dkim-keys:/etc/opendkim/keys
    restart: unless-stopped

volumes:
  lanqin-data:
  maildata:
  dkim-keys:
