protocols = imap lmtp
listen = *
base_dir = /var/run/dovecot/

log_path = /dev/stderr
info_log_path = /dev/stdout

ssl = yes
ssl_cert = </etc/ssl/certs/ssl-cert-snakeoil.pem
ssl_key = </etc/ssl/private/ssl-cert-snakeoil.key

mail_home = /var/mail/vhosts/%d/%n
namespace inbox {
  inbox = yes
  mailbox Drafts { special_use = \Drafts }
  mailbox Sent { special_use = \Sent }
  mailbox Trash { special_use = \Trash }
  mailbox Archive { special_use = \Archive }
  mailbox Spam { special_use = \Junk }
}

passdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}
userdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}

service imap-login {
  inet_listener imaps { port = 993 ssl = yes }
}

service lmtp {
  inet_listener lmtp { address = 0.0.0.0 port = 24 }
}

service auth {
  inet_listener postfix-auth {
    address = 0.0.0.0
    port = 12345
  }
}

protocol lmtp {
  postmaster_address = postmaster@localhost
}
